apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-oval-debian
spec:
  template:
    spec:
      containers:
      - name: fetch-oval-debian
        image: gcr.io/[PROJECT ID]/vuls/goval-dictionary
        command: ["/bin/sh","-c"]
        args:
          - goval-dictionary fetch-debian 7 8 9 10
        volumeMounts:
        - name: vuls-db
          mountPath: /vuls
      restartPolicy: Never
      volumes:
      - name: vuls-db
        persistentVolumeClaim:
          claimName: vulnerability-db